In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from keras.layers import Dense
from keras.models import Sequential
from keras.utils import to_categorical
import matplotlib as plt

In [2]:
df=pd.read_csv("D:\VERZEO (AI ML)\AI ML\HEART DISEASE\heart.csv")   #to load the dataset of ML model
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [4]:
y=df["target"]     #storing the target column in the Y variable

In [5]:
target=to_categorical(y)

In [6]:
X=df.drop("target",axis=1)   #now X contains all the column except "target". "axis=1" indicates python to search in columns

In [7]:
X   #now X just contains the features 

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

# Specify the Architecture

In [8]:
model=Sequential()
model.add(Dense(200,activation="relu", input_shape=(13,)))   #13 signifies your feature columns
model.add(Dense(200,activation="relu")) 
model.add(Dense(300,activation="relu"))
model.add(Dense(2, activation="softmax"))


In [9]:
model.compile(optimizer="adam", loss="categorical_crossentropy",metrics=["accuracy"])   
#adam initiates Gradient Descent "mean square" to ananlyse loss

# Fit the model

In [10]:
model.fit(X,target, epochs=50) #always pass Features,Targets therefore X,y "epochs" to know how much time to run

Epoch 1/50
10/10 [==============================] - 1s 3ms/step - loss: 6.9990 - accuracy: 0.5321
Epoch 2/50
10/10 [==============================] - 0s 3ms/step - loss: 1.2775 - accuracy: 0.6247
Epoch 3/50
10/10 [==============================] - 0s 3ms/step - loss: 0.7332 - accuracy: 0.6060
Epoch 4/50
10/10 [==============================] - 0s 3ms/step - loss: 0.5959 - accuracy: 0.6973
Epoch 5/50
10/10 [==============================] - 0s 3ms/step - loss: 0.6480 - accuracy: 0.6765
Epoch 6/50
10/10 [==============================] - 0s 4ms/step - loss: 0.8897 - accuracy: 0.5895
Epoch 7/50
10/10 [==============================] - 0s 3ms/step - loss: 0.9666 - accuracy: 0.5831
Epoch 8/50
10/10 [==============================] - 0s 3ms/step - loss: 0.8545 - accuracy: 0.6138
Epoch 9/50
10/10 [==============================] - 0s 3ms/step - loss: 0.8613 - accuracy: 0.6293
Epoch 10/50
10/10 [==============================] - 0s 3ms/step - loss: 0.7314 - accuracy: 0.6740
Epoch 11/50
10/10 [

In [11]:
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [12]:
data=pd.DataFrame({"age":[78],"sex":[1],"cp":[1],"trestbps":[130],"chol":[233],"fbs":[0],
                  "restecg":[1],"thalach":[234], "exang":[0],"oldpeak":[2.3],"slope":[2],"ca":[0],"thal":[1]})

In [13]:
data_2=pd.DataFrame({"age":[23],"sex":[0],"cp":[1],"trestbps":[100],"chol":[133],"fbs":[0],
                  "restecg":[0],"thalach":[114], "exang":[0],"oldpeak":[0.3],"slope":[0],"ca":[0],"thal":[1]})

In [14]:
data.shape

(1, 13)

In [15]:
X.shape

(303, 13)

In [16]:
y.shape

(303,)

In [17]:
target.shape

(303, 2)

In [18]:
model.predict(data)

array([[0.00444394, 0.99555606]], dtype=float32)

In [19]:
model.predict(data_2)

array([[0.06911479, 0.93088526]], dtype=float32)

In [20]:
data_3=pd.DataFrame({"age":[58],"sex":[1],"cp":[3],"trestbps":[230],"chol":[233],"fbs":[1],
                  "restecg":[1],"thalach":[234], "exang":[1],"oldpeak":[2.3],"slope":[2],"ca":[1],"thal":[1]})

In [21]:
model.predict(data_3)

array([[0.00354037, 0.99645966]], dtype=float32)